In [4]:
print("dd")



dd


In [5]:
1+1


2

In [8]:
d = {"k1": [1,2,3]}


In [12]:
my_list = d['k1'][1]

In [13]:
my_list

2

In [7]:
print("j")

j


In [15]:
{1,1,1,1,1,2,3}

{1, 2, 3}

In [17]:
for num in range(0,9):
    print(num)
list = 

0
1
2
3
4
5
6
7
8


In [19]:
list = list(range(0,20))
print(list)


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]


In [20]:
x = []
for num in list:
    x.append(num**2)

In [21]:
print(x)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361]


In [31]:
list(map(lambda num: num**2,x))

TypeError: 'list' object is not callable

In [29]:
print (f)


In [30]:
x


[0,
 1,
 4,
 9,
 16,
 25,
 36,
 49,
 64,
 81,
 100,
 121,
 144,
 169,
 196,
 225,
 256,
 289,
 324,
 361]

In [32]:
seq = [1,2,3,4,5]
list(map(lambda num: num*3,seq))

TypeError: 'list' object is not callable

In [33]:
t = lambda var:var**2

In [34]:
t(3)


9

In [35]:
t(seq)


TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [37]:
list(map(t, seq))

TypeError: 'list' object is not callable

In [38]:
def times2(var):
    return var*2

In [39]:
times2(10)

20

In [40]:
seq


[1, 2, 3, 4, 5]

In [44]:
list(map(times2,seq))


TypeError: 'list' object is not callable

In [45]:
s = 'my name is Jorge'

In [46]:
s.lower()

'my name is jorge'

In [47]:
s.upper()

'MY NAME IS JORGE'

In [48]:
s.split()

['my', 'name', 'is', 'Jorge']

In [49]:
my_list = [1,2,3]


In [50]:
import numpy as np

In [52]:
arr = np.array(my_list)

In [53]:
arr


array([1, 2, 3])

In [54]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [55]:
my_mat


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [56]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
np.arange(0,15,3)

array([ 0,  3,  6,  9, 12])

In [60]:
np.zeros(4)

array([0., 0., 0., 0.])

In [62]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [63]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [64]:
np.ones((6,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [72]:
np.linspace(0,2)

array([0.        , 0.04081633, 0.08163265, 0.12244898, 0.16326531,
       0.20408163, 0.24489796, 0.28571429, 0.32653061, 0.36734694,
       0.40816327, 0.44897959, 0.48979592, 0.53061224, 0.57142857,
       0.6122449 , 0.65306122, 0.69387755, 0.73469388, 0.7755102 ,
       0.81632653, 0.85714286, 0.89795918, 0.93877551, 0.97959184,
       1.02040816, 1.06122449, 1.10204082, 1.14285714, 1.18367347,
       1.2244898 , 1.26530612, 1.30612245, 1.34693878, 1.3877551 ,
       1.42857143, 1.46938776, 1.51020408, 1.55102041, 1.59183673,
       1.63265306, 1.67346939, 1.71428571, 1.75510204, 1.79591837,
       1.83673469, 1.87755102, 1.91836735, 1.95918367, 2.        ])

In [74]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [76]:
np.random.rand(5,5)

array([[0.16831433, 0.43631972, 0.6676205 , 0.44953761, 0.66886174],
       [0.28300826, 0.10022027, 0.01950616, 0.13929329, 0.67884771],
       [0.7048457 , 0.21966887, 0.42716393, 0.23170214, 0.27068361],
       [0.8811074 , 0.07993006, 0.80586199, 0.84337686, 0.49824541],
       [0.03917301, 0.31990658, 0.78227039, 0.8093184 , 0.32580748]])

In [133]:
np.random.randint(1,1000)

147

In [79]:
arr = np.arange(25)

In [80]:
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [81]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [82]:
arr.max()

24

In [83]:
arr.shape

(25,)

In [84]:
arr = arr.reshape(5,5)

In [85]:
arr.shape

(5, 5)

In [86]:
import numpy as np


In [87]:
arr = np.arange(11)

In [88]:
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [90]:
arr[10]

10

In [93]:
arr[0:5] = 100

In [94]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [95]:
arr = np.arange(11)


In [96]:
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [97]:
arr_2d = np.array([[5,10,15],[20,25,30],[30,35,40]])

In [98]:
arr_2d


array([[ 5, 10, 15],
       [20, 25, 30],
       [30, 35, 40]])

In [103]:
arr_2d[2]

array([30, 35, 40])

In [104]:
arr = np.arange(1,11)


In [105]:
arr


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [106]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [107]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [108]:
arr_2d = np.arange(50).reshape(5,10)

In [112]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [121]:
arr_2d[2][3:5]

array([23, 24])

In [122]:
arr_2d + 3

array([[ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22],
       [23, 24, 25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48, 49, 50, 51, 52]])

In [123]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [128]:
arrxx = arr_2d**2

In [130]:
np.sqrt(arrxx)

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14., 15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24., 25., 26., 27., 28., 29.],
       [30., 31., 32., 33., 34., 35., 36., 37., 38., 39.],
       [40., 41., 42., 43., 44., 45., 46., 47., 48., 49.]])

In [131]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [132]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [136]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [137]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [138]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [148]:
np.random.rand(10,10,0.1)

TypeError: 'float' object cannot be interpreted as an integer

In [153]:
np.linspace(0.01,1,100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [154]:
np.linspace(0.01,1,100)

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

In [155]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [156]:
mat = np.arange(1,26).reshape(5,5)

In [157]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [166]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [168]:
mat[3,4]

20

In [171]:
mat[0:3,1].reshape(3,1)

array([[ 2],
       [ 7],
       [12]])

In [172]:
mat[4,:]

array([21, 22, 23, 24, 25])

In [173]:
mat[3:5,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [174]:
np.sum(mat)

325

In [175]:
np.std(mat)

7.211102550927978

In [176]:
np.sum(mat, axis=0)

array([55, 60, 65, 70, 75])

In [177]:
import panda as pd


ModuleNotFoundError: No module named 'panda'

In [178]:
import pandas as pd


In [179]:
np.random.seed(101)

In [180]:
df = pd.DataFrame(randn(5,4),[A,B,C,D,E],[W,X,Y,Z])

NameError: name 'randn' is not defined

In [181]:
from numpy.random import rand'

In [183]:
df = pd.DataFrame(randn(5,4),['A','B','C','D','E'],['W','X','Y','Z'])

In [184]:
df

W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [185]:
df2 = pd.DataFrame(randn(5,4))

In [186]:
df2


0         1         2         3
0 -0.993263  0.196800 -1.136645  0.000366
1  1.025984 -0.156598 -0.031579  0.649826
2  2.154846 -0.610259 -0.755325 -0.346419
3  0.147027 -0.479448  0.558769  1.024810
4 -0.925874  1.862864 -1.133817  0.610478

In [187]:
df['W']

A    0.302665
B   -0.134841
C    0.807706
D   -0.497104
E   -0.116773
Name: W, dtype: float64

In [188]:
df.X


A    1.693723
B    0.390528
C    0.072960
D   -0.754070
E    1.901755
Name: X, dtype: float64

In [189]:
df['New'] = df['W'] + df['X']

In [190]:
df


W         X         Y         Z       New
A  0.302665  1.693723 -1.706086 -1.159119  1.996388
B -0.134841  0.390528  0.166905  0.184502  0.255687
C  0.807706  0.072960  0.638787  0.329646  0.880666
D -0.497104 -0.754070 -0.943406  0.484752 -1.251174
E -0.116773  1.901755  0.238127  1.996652  1.784981

In [191]:
df.drop('E')

W         X         Y         Z       New
A  0.302665  1.693723 -1.706086 -1.159119  1.996388
B -0.134841  0.390528  0.166905  0.184502  0.255687
C  0.807706  0.072960  0.638787  0.329646  0.880666
D -0.497104 -0.754070 -0.943406  0.484752 -1.251174

In [192]:
df

W         X         Y         Z       New
A  0.302665  1.693723 -1.706086 -1.159119  1.996388
B -0.134841  0.390528  0.166905  0.184502  0.255687
C  0.807706  0.072960  0.638787  0.329646  0.880666
D -0.497104 -0.754070 -0.943406  0.484752 -1.251174
E -0.116773  1.901755  0.238127  1.996652  1.784981

In [193]:
df.loc['B','Y']

0.16690463609281317

In [195]:
df.iloc[2]

W      0.807706
X      0.072960
Y      0.638787
Z      0.329646
New    0.880666
Name: C, dtype: float64

In [196]:
df.loc['C']

W      0.807706
X      0.072960
Y      0.638787
Z      0.329646
New    0.880666
Name: C, dtype: float64

In [197]:
t = np.linspace(0, 40, 1000) # start, finish, n points

In [198]:
t

array([ 0.        ,  0.04004004,  0.08008008,  0.12012012,  0.16016016,
        0.2002002 ,  0.24024024,  0.28028028,  0.32032032,  0.36036036,
        0.4004004 ,  0.44044044,  0.48048048,  0.52052052,  0.56056056,
        0.6006006 ,  0.64064064,  0.68068068,  0.72072072,  0.76076076,
        0.8008008 ,  0.84084084,  0.88088088,  0.92092092,  0.96096096,
        1.001001  ,  1.04104104,  1.08108108,  1.12112112,  1.16116116,
        1.2012012 ,  1.24124124,  1.28128128,  1.32132132,  1.36136136,
        1.4014014 ,  1.44144144,  1.48148148,  1.52152152,  1.56156156,
        1.6016016 ,  1.64164164,  1.68168168,  1.72172172,  1.76176176,
        1.8018018 ,  1.84184184,  1.88188188,  1.92192192,  1.96196196,
        2.002002  ,  2.04204204,  2.08208208,  2.12212212,  2.16216216,
        2.2022022 ,  2.24224224,  2.28228228,  2.32232232,  2.36236236,
        2.4024024 ,  2.44244244,  2.48248248,  2.52252252,  2.56256256,
        2.6026026 ,  2.64264264,  2.68268268,  2.72272272,  2.76

In [199]:
pwd

'/Users/jorayala/Library/CloudStorage/OneDrive-Cisco/2023/Python/Data Analitycs Udemy/Refactored_Py_DS_ML_Bootcamp-master'

In [200]:
ls

00-Welcome to the Course.ipynb         14-K-Nearest-Neighbors/
01-Python-Crash-Course/                15-Decision-Trees-and-Random-Forests/
02-Python-for-Data-Analysis-NumPy/     16-Support-Vector-Machines/
03-Python-for-Data-Analysis-Pandas/    17-K-Means-Clustering/
04-Pandas-Exercises/                   18-Principal-Component-Analysis/
05-Data-Visualization-with-Matplotlib/ 19-Recommender-Systems/
06-Data-Visualization-with-Seaborn/    20-Natural-Language-Processing/
07-Pandas-Built-in-Data-Viz/           21-Big-Data-and-Spark/
08-Plotly-and-Cufflinks/               22-Deep Learning/
09-Geographical-Plotting/              23-EXTRA-NOTES-SciPy/
10-Data-Capstone-Projects/             Pierian_Data_Logo.png
11-Linear-Regression/                  README.md
13-Logistic-Regression/                Untitled.ipynb
